name: Backup Firestore

on:
  schedule:
    - cron:  42 3 * * *

env:
  PROJECT_ID: slr67-qa
  BUCKET: gs://slr67-qa-backups
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
